services:
  - type: web
    name: rtb-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r backend/requirements.txt && python backend/create_db.py
    startCommand: cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT main:app
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDuEdAygLcQ4aEuq2Vqj-9Kl0qZpJcg3A8
      - key: PYTHON_VERSION
        value: 3.10.0
